name: Feature request
description: Suggest an idea for this project
title: ""
labels: ["enhancement"]

body:
    - type: dropdown
      id: type
      attributes:
          label: Is this feature request for SmartifyOS or the Miata example project?
          options:
              - SmartifyOS
              - Miata Example Project
      validation:
          required: true

    - type: textarea
      id: description
      attributes:
          label: Describe the feature you'd like
          placeholder: "A clear and concise description of what you want to happen."
      validation:
          required: true

    - type: textarea
      id: additional
      attributes:
          label: Additional context
          placeholder: Add any other context or screenshots about the feature request here.

    - type: textarea
      id: additional
      attributes:
          label: Additional context
          placeholder: Add any other context or screenshots about the feature request here.
